spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password:  
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://103.200.30.232:3306/sms
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    

    
    
    